steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/skaffold:16.0-helm-2.17-2', '--tag=gcr.io/$PROJECT_ID/skaffold:latest', '.']

images:
    - 'gcr.io/$PROJECT_ID/skaffold:16.0-helm-2.17-2'
    - 'gcr.io/$PROJECT_ID/skaffold:latest'
tags: ['cloud-builders-community']
