steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/skaffold:1.7.0', '--tag=gcr.io/$PROJECT_ID/skaffold:latest', '.']

images:
    - 'gcr.io/$PROJECT_ID/skaffold:1.7.0'
    - 'gcr.io/$PROJECT_ID/skaffold:latest'
tags: ['cloud-builders-community']
